/* Creamos algunos usuarios con sus roles */
INSERT INTO USUARIOS(ID, DIRECCION, CELULAR, EMAIL, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE, CONTRASENA, TIPO_USUARIO, USUARIO, ACTIVO) VALUES (1, 'Calle Uno', '5554233176',  'mario@m1.com', 'López', 'García', 'Mario', '$2a$10$QNG4wVxGlEmaRDW9pSp9gOdy6QsuWbD3DKUrXU3Y3ONSoUmPOHZz.', 'ADMIN', 'mariodb', 1);
	
INSERT INTO USUARIOS(ID, DIRECCION, CELULAR, EMAIL, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE, CONTRASENA, TIPO_USUARIO, USUARIO, ACTIVO) VALUES (2, 'Calle Dos', '5558903421', 'maria@m2.com', 'Soto', 'Sánchez', 'María', '$2a$10$WSLp6qILSfaIE9fLHuauEueVmatE.lAPZdBblGEDw1xkrg8/aAS8y', 'USER', 'mariadb', 1);	

