/* Creamos algunos usuarios con sus roles */
INSERT INTO USUARIOS(ID, DIRECCION, CELULAR, EMAIL, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE, CONTRASENA, TIPO_USUARIO, USUARIO, ACTIVO) VALUES (1, 'Francisco Morles 887', '5554233176',  'mario@banobras.gob.mx', 'López', 'García', 'Mario', '$2a$10$QNG4wVxGlEmaRDW9pSp9gOdy6QsuWbD3DKUrXU3Y3ONSoUmPOHZz.', 'ADMIN', 'mariodb', 1);
	
INSERT INTO USUARIOS(ID, DIRECCION, CELULAR, EMAIL, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE, CONTRASENA, TIPO_USUARIO, USUARIO, ACTIVO) VALUES (2, 'Av. Universidad 525', '5558903421', 'maria@banobras.gob.mx', 'Soto', 'Sánchez', 'María', '$2a$10$WSLp6qILSfaIE9fLHuauEueVmatE.lAPZdBblGEDw1xkrg8/aAS8y', 'USER', 'mariadb', 1);	

INSERT INTO USUARIOS(ID, DIRECCION, CELULAR, EMAIL, APELLIDO_PATERNO, APELLIDO_MATERNO, NOMBRE, CONTRASENA, TIPO_USUARIO, USUARIO, ACTIVO) VALUES (3, 'Estampado 93', '5558903421', 'jorge@banobras.gob.mx', 'Rivera', 'Morlaes', 'Alma Rosa', '$2a$10$WSLp6qILSfaIE9fLHuauEueVmatE.lAPZdBblGEDw1xkrg8/aAS8y', 'USER', 'alamadb', 0);	

